### ISSUE TITLE
报错 TypeError: force_insert must be a bool or tuple.

### ISSUE THREAD

**Issue by everinlove** [mxdabc/epg#1]
请问一下运行时报错这个需要怎样解决呢  没找到相关的
root@armbian:/www/wwwroot/DIYP/epg# python3 main.py
Traceback (most recent call last):
  File "/www/wwwroot/DIYP/epg/main.py", line 20, in <module>
    start_crawl()
  File "/www/wwwroot/DIYP/epg/crawl/crawl.py", line 47, in main
    log('%s\t第%s天 共有：%s 个频道节目表需要获取' % (dt.strftime('%Y-%m-%d'), d + 1, channel_no))
  File "/www/wwwroot/DIYP/epg/utils/aboutdb.py", line 14, in log
    dbinfo.save()
  File "/www/wwwroot/DIYP/epg/web/models.py", line 241, in save
    super().save(self, *args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 905, in save_base
    force_insert = self._validate_force_insert(force_insert)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 850, in _validate_force_insert
    raise TypeError("force_insert must be a bool or tuple.")
TypeError: force_insert must be a bool or tuple.

**Comment by mxdabc** [comment]
目前已知在Arm平台上运行会有此错误，请您贴出您系统的详细信息！

**Comment by everinlove** [comment]
Armbian OS 24.5.0 Bookworm with Linux 6.1.81-ophub
Linux version 6.1.81-ophub (root@fv-az1530-811) (aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009, GNU ld (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 2.41.0.20231009) #1 SMP Wed Mar  6 23:20:44 EST 2024

**Comment by mxdabc** [comment]
> Armbian OS 24.5.0 Bookworm with Linux 6.1.81-ophub Linux version 6.1.81-ophub (root@fv-az1530-811) (aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009, GNU ld (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 2.41.0.20231009) #1 SMP Wed Mar 6 23:20:44 EST 2024

很明显，你这是Arm，运行肯定不成功，请换一个amd64架构的

**Comment by mxdabc** [comment]
如果您还有疑问，请再开一个Issues！此Issues将关闭！

**Comment by mxdabc** [comment]
# 有问题请回复此Issues！

**Comment by tigerainiuniu** [comment]
sqlite shoud use some version ？

**Comment by mxdabc** [comment]
> sqlite shoud use some version ？
> 
> when i execute sqlite3 version.
> 
> [root@localhost epg]# sqlite3 version SQLite version 3.8.3 2014-02-03 14:04:11
> 
> but , django.db.utils.NotSupportedError: deterministic=True requires SQLite 3.8.3 or higher
> 
> so,this sqlite shoud use some version ?

You don't need to install the SQLite database software externally, just use a Python script to call the db.sqlite3 file.
