### ISSUE TITLE
tvsou SSL错误

### ISSUE THREAD

**Issue by jinglingxiaoguin** [mxdabc/epg#5]
更换 tvsou 来源后，获取信息失败,spider-tvsou-连接失败，HTTPSConnectionPool(host='www.tvsou.com', port=443): Max retries exceeded with url: /epg/NNTV-e211ffe8/w4 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))
请问大佬这个怎么解决？

**Comment by mxdabc** [comment]
```python
pip install urllib3=1.26.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
```
如果Linux提示需要加`--break-system-package`，加上即可

**Comment by mxdabc** [comment]
已修复

**Comment by mxdabc** [comment]
[mxd's EPG 报错 [SSL: CERTIFICATE_VERIFY_FAILED]](https://blog.mxdyeah.top/mxdyeah_blog_post/55.html)
参照这里
